/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ArchivalItem, NivelDescripcion, TipoRecurso, CondicionAcceso, EstadoElaboracion } from "./types";

export const mockItems: ArchivalItem[] = [
  {
    id: "AR-ARCH-001",
    identificacion: {
      codigoReferencia: "AR-ARCH-001/DDA-UNT",
      titulo: "Acta de Fundación de la Universidad Nacional de Tucumán",
      fechaCreacion: "1914-05-25",
      nivelDescripcion: NivelDescripcion.ITEM,
      tipoRecurso: TipoRecurso.PAPEL,
      volumenSoporte: "1 folio, Papel pergamino",
      identificadorAccesoNAS: "https://nas.unt.edu.ar/dda/acta_fundacion_001.pdf",
      identificadorExterno: "DOI:10.1234/dda.arch.001",
      identificadorRepositorio: "ISDIAH-UNT-DDA",
      ubicacionDeposito: "Edificio Central, Caja Fuerte 01",
    },
    contexto: {
      productor: "Juan B. Terán",
      fechasProductor: "1880 - 1938",
      historiaInstitucional: "Fundador de la UNT, rector entre 1914 y 1929.",
      historiaArchivistica: "Custodiado por la Secretaría General hasta su transferencia al DDA en 1980.",
      formaIngreso: "Transferencia administrativa",
    },
    contenido: {
      alcanceContenido: "Documento fundacional que establece los principios y la estructura inicial de la universidad.",
      palabrasClave: ["Fundación", "UNT", "Juan B. Terán", "Tucumán"],
      sistemaOrganizacion: "Cronológico / Institucional",
      valoracionSeleccion: "Conservación permanente",
      plazoConservacion: "Indefinido",
    },
    tecnica: {
      extensionSoporte: "1 folio",
      formatoDigital: "application/pdf",
      hashDigital: "d41d8cd98f00b204e9800998ecf8427e",
      estadoConservacion: "Excelente",
      requisitosSoftware: "Adobe Acrobat Reader o visor de PDF",
    },
    acceso: {
      condicionesAcceso: CondicionAcceso.PUBLICO,
      condicionesReproduccion: "Permitida bajo supervisión.",
      licenciaUso: "Creative Commons BY-NC-SA 4.0",
      lenguaEscritura: "Español, Caligrafía manuscrita",
      disponibilidadOriginales: "Original físico en DDA-UNT",
      publicacionesRelacionadas: "Libro de Oro de la UNT, 1964.",
    },
    control: {
      reglasConvenciones: "ISAD(G), ISAAR(CPF), ISDIAH",
      estadoElaboracion: EstadoElaboracion.FINAL,
      fechaDescripcion: "2024-01-15",
      institucionResponsable: "Departamento de Documentación y Archivo - UNT",
      responsableFicha: "Lic. María Archivista",
      notas: "Restaurado en 2010 por el equipo de conservación.",
    },
    thumbnailUrl: "https://picsum.photos/seed/archive1/400/300",
  },
  {
    id: "AR-ARCH-AV-042",
    identificacion: {
      codigoReferencia: "AR-ARCH-AV-042/DDA-UNT",
      titulo: "Discurso de Apertura del Ciclo Lectivo 1968",
      fechaCreacion: "1968-03-10",
      nivelDescripcion: NivelDescripcion.ITEM,
      tipoRecurso: TipoRecurso.VIDEO,
      volumenSoporte: "1 rollo de película 16mm, Digitalizado 1.2 GB",
      identificadorAccesoNAS: "https://nas.unt.edu.ar/dda/av/discurso_1968.mp4",
      identificadorExterno: "ARK:/12345/dda.av.042",
      identificadorRepositorio: "ISDIAH-UNT-DDA",
      ubicacionDeposito: "Servidor NAS DDA - Volumen Multimedia",
    },
    contexto: {
      productor: "Departamento de Cine y TV - UNT",
      fechasProductor: "1955 - Presente",
      creditosProduccion: "Director: Roberto Cineasta; Cámara: Luis Imagen",
      historiaInstitucional: "El Departamento de Cine fue pionero en la región.",
      historiaArchivistica: "Recuperado de los depósitos de la Escuela de Cine en 2010.",
      formaIngreso: "Donación",
    },
    contenido: {
      alcanceContenido: "Registro audiovisual del acto académico en el patio central de la UNT.",
      palabrasClave: ["Discurso", "1968", "Patio Central", "Acto Académico"],
      sistemaOrganizacion: "Serie Audiovisual - Actos Públicos",
      valoracionSeleccion: "Conservación permanente",
      plazoConservacion: "Permanente",
      puntosAccesoTimecodes: [
        { time: "00:00:00", label: "Inicio del acto" },
        { time: "00:05:20", label: "Discurso del Rector" },
        { time: "00:12:45", label: "Cierre y aplausos" },
      ],
    },
    tecnica: {
      extensionSoporte: "1 rollo 16mm",
      formatoDigital: "video/mp4",
      duracion: "00:15:30",
      hashDigital: "7b5871c27f1930aa2f02ff08310355b5",
      caracteristicasVideo: {
        resolucion: "1080p",
        aspectRatio: "4:3",
        bitrate: "5000 kbps",
        fps: "24",
      },
      caracteristicasAudio: {
        canales: "Mono",
        sampleRate: "44.1 kHz",
      },
      estadoConservacion: "Restaurado digitalmente",
      requisitosSoftware: "VLC Media Player o navegador moderno",
    },
    acceso: {
      condicionesAcceso: CondicionAcceso.PUBLICO,
      condicionesReproduccion: "Uso institucional y educativo.",
      licenciaUso: "Dominio Público",
      lenguaEscritura: "Español (Audio)",
      disponibilidadOriginales: "Copia digital en NAS, original físico en Bóveda Fría",
    },
    control: {
      reglasConvenciones: "ISAD(G), FIAF, FIAT",
      estadoElaboracion: EstadoElaboracion.REVISADO,
      fechaDescripcion: "2024-02-20",
      institucionResponsable: "Departamento de Documentación y Archivo - UNT",
      responsableFicha: "Téc. Juan Audiovisual",
      notas: "Audio mejorado mediante filtros digitales en 2023.",
    },
    thumbnailUrl: "https://picsum.photos/seed/video1/400/300",
  },
  {
    id: "AR-ARCH-PH-105",
    identificacion: {
      codigoReferencia: "AR-ARCH-PH-105/DDA-UNT",
      titulo: "Construcción del Pabellón de Ingeniería",
      fechaCreacion: "1945-06-12",
      nivelDescripcion: NivelDescripcion.ITEM,
      tipoRecurso: TipoRecurso.FOTOGRAFIA,
      volumenSoporte: "1 negativo de vidrio, Digitalizado 45 MB",
      identificadorAccesoNAS: "https://nas.unt.edu.ar/dda/fotos/ing_1945.tiff",
      identificadorExterno: "ARK:/12345/dda.ph.105",
      identificadorRepositorio: "ISDIAH-UNT-DDA",
      ubicacionDeposito: "Archivo Fotográfico, Gaveta 12",
    },
    contexto: {
      productor: "Oficina de Arquitectura UNT",
      fechasProductor: "1940 - 1970",
      historiaInstitucional: "Responsable del diseño del campus universitario.",
      historiaArchivistica: "Transferido desde la Facultad de Ciencias Exactas.",
      formaIngreso: "Transferencia",
    },
    contenido: {
      alcanceContenido: "Vista panorámica de los cimientos del pabellón de ingeniería.",
      palabrasClave: ["Arquitectura", "Ingeniería", "Campus", "Construcción"],
      sistemaOrganizacion: "Colección Fotográfica - Obras",
      valoracionSeleccion: "Conservación permanente",
    },
    tecnica: {
      extensionSoporte: "1 negativo 9x12",
      formatoDigital: "image/tiff",
      hashDigital: "8e2938127f1930aa2f02ff08310355c6",
      estadoConservacion: "Fragilidad media por desprendimiento de emulsión",
      requisitosSoftware: "Visor de imágenes de alta resolución",
    },
    acceso: {
      condicionesAcceso: CondicionAcceso.PUBLICO,
      condicionesReproduccion: "Prohibido el uso comercial.",
      licenciaUso: "CC BY-NC 4.0",
      lenguaEscritura: "N/A",
      disponibilidadOriginales: "Original físico en DDA-UNT",
    },
    control: {
      reglasConvenciones: "ISAD(G), ISDIAH",
      estadoElaboracion: EstadoElaboracion.FINAL,
      fechaDescripcion: "2023-11-05",
      institucionResponsable: "Departamento de Documentación y Archivo - UNT",
      responsableFicha: "Lic. Ana Fototeca",
      notas: "Limpieza química realizada en 2022.",
    },
    thumbnailUrl: "https://picsum.photos/seed/photo1/400/300",
  }
];
